config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get 'create', to: 'pitches#new', as: 'create'

  resources :users, only: [:index, :update]
  resources :feedbacks, only: [:index]

  namespace :api do
    namespace :pitchlove do

      resources :pitches do
        collection do
          get "all"
          post "create"
          post "data"

        end
      end

      resources :users do
        collection do
          get "all"
          post "signin"
        end
      end

      resources :feedbacks do
        collection do
          get "all"
        end
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @user = User.new()
  end


  # def resource_name
  #   :user
  # end
  #
  # def resource
  #   @resource ||= User.new
  # end
  #
  # def devise_mapping
  #   @devise_mapping ||= Devise.mappings[:user]
  # end

end

app/views/welcome/index.html.erb
    <!-- Header -->
    <header>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-text">
                        <h2>Become a startup founder!</h2>
                        <h3 class="skills">Get feedback from customers + experts + investors using pitchLove.</h3>
                    </div>
                </div>
            </div>


            <div class="panel-pop" id="signup">
              <h2>Register Now</h2>
                <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                  <%= devise_error_messages! %>

                  <div class="field">
                    <%= f.label :email %><br />
                    <%= f.email_field :email, autofocus: true %>
                  </div>

                  <div class="field">
                    <%= f.label :password %>
                    <% if @minimum_password_length %>
                    <em>(<%= @minimum_password_length %> characters minimum)</em>
                    <% end %><br />
                    <%= f.password_field :password, autocomplete: "off" %>
                  </div>

                  <div class="field">
                    <%= f.label :password_confirmation %><br />
                    <%= f.password_field :password_confirmation, autocomplete: "off" %>
                  </div>

                  <%= f.hidden_field :registered, value: true %>

                  <div class="actions">
                    <%= f.submit "Sign up" %>
                  </div>
                <% end %>
            </div><!-- End signup -->



            <div class="panel-pop" id="signin">
              <h2>Sign In <br>
              (Enter either email address or username)</h2>

              <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
              <!-- <%#= form_for(resource, url:signin_api_pitchlove_users_path(resource)) do |f| %> -->
                <div class="field">
                  <%= f.label :email %><br />
                  <%= f.email_field :email, autofocus: true %>
                </div>

                <div class="field">
                  <%= f.label :username %><br />
                  <%= f.email_field :username, autofocus: true %>
                </div>

                <div class="field">
                  <%= f.label :password %><br />
                  <%= f.password_field :password, autocomplete: "off", autofocus: false %>
                </div>

                <% if devise_mapping.rememberable? -%>
                  <div class="field">
                    <%= f.check_box :remember_me %>
                    <%= f.label :remember_me %>
                  </div>
                <% end -%>

                <div class="actions">
                  <%= f.submit "Log in" %>
                </div>
              <% end %>
            </div><!-- End signin -->

                <div class="row welcome">
                    <div class="row main-button"><!-- Before login -->
                      <% if !current_user %>
                        <div class="col-sm-8 col-sm-offset-2"><a class="button-text btn btn-lg btn-success btn-block signup" href="/create">Sign up</a></div>
                        <p>&nbsp</p>
                        <div class="col-sm-8 col-sm-offset-2"><a class="button-text btn btn-lg btn-success btn-block signin" href="/create">Log in</a></div>
                        <!--<p><?php print_r($_SESSION['DB'].$_SESSION['COUNT']); ?></p>-->
                        <!--<div><a class="btn btn-lg btn-success" href="logout.php">Logout</a></div>-->
                      <% else %>
                        <div class="col-md-8 col-md-offset-2 text-center jumbotron">
                          <h3>Welcome to pitchLove <?php echo $_SESSION['FNAME']; ?>!</h3>
                            <div class="col-md-6 col-md-offset-3">
                                <a class="btn btn-lg btn-success btn-block" href="/create">Click to Enter</a>
                            </div>
                            <div class="col-md-4 col-md-offset-4">
                                <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn btn-lg btn-success btn-block logout") %>
                            </div>
                      <% end %>
                    </div>
                    </div>
                    <div class="jumbotron row">
                        <div class="col-sm-12">
                            <h3>How to Use pitchLove:</h3>
                        </div>
                        <div class="col-sm-3">
                            <h4>Create a pitch</h4>
                            <hr>
                            <p>Log in, sign up, and create a pitch. </p>
                        </div>
                        <div class="col-sm-3">
                            <h4>Share your pitch</h4>
                            <hr>
                            <p>Share your pitch URL with your email and social media list for more feedback and insights. If you want, we'll share it ours too!</p>
                        </div>
                        <div class="col-sm-3">
                            <h4>Get data + feedback</h4>
                            <hr>
                            <p>Our API calculates the feedback and data you receive and it converts it into actionable reports to help steer your startup.</p>
                        </div>
                        <div class="col-sm-3">
                            <h4>Improve your pitch or get pre-orders</h4>
                            <hr>
                            <p>You can improve to reach more customers or you can move to the next stage in our process to the pre-order stage.</p>
                        </div>
                    </div>

        </div>
    </header>

    <!-- Contact Section -->
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Contact Us</h2>
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1">
                    <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                    <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                    <form name="sentMessage" id="contactForm" novalidate>
                        <div class="row well control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Name</label>
                                <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row well control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Email Address</label>
                                <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row well control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Phone Number</label>
                                <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row well control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Message</label>
                                <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <br>
                        <div id="success"></div>
                        <div class="row">
                            <div class="form-group col-xs-6 col-xs-offset-3">
                                <button type="submit" class="btn btn-lg btn-success btn-block">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>